name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: What
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Docker Login LCAS
      uses: docker/login-action@v2
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: lcas.lincoln.ac.uk
        # Username used to log against the Docker registry
        username: ${{ secrets.LCAS_REGISTRY_PUSHER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.LCAS_REGISTRY_TOKEN }}
    - name: Docker Login dockerhub
      uses: docker/login-action@v2
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push 
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: lcas.lincoln.ac.uk/mhanheide/graphotti:${{ env.BRANCH }}
        build-args: |
            BRANCH=${{ env.BRANCH }}
